routes/front.php
<?php
AdvancedRoute::controller('auth', 'AuthController');
AdvancedRoute::controller('profile', 'ProfileController');
AdvancedRoute::controller('notifications', 'NotificationsController');
AdvancedRoute::controller('roles', 'RolesController');
AdvancedRoute::controller('countries', 'CountriesController');
AdvancedRoute::controller('currencies', 'CurrenciesController');
AdvancedRoute::controller('users', 'UsersController');
AdvancedRoute::controller('posts', 'PostsController');
AdvancedRoute::controller('dashboard', 'DashBoardController');
AdvancedRoute::controller('events', 'EventsController');
AdvancedRoute::controller('groups', 'GroupsController');
AdvancedRoute::controller('programs', 'ProgramsController');
AdvancedRoute::controller('items', 'ItemsController');
AdvancedRoute::controller('contacts', 'ContactsController');
AdvancedRoute::controller('children', 'ChildrenController');
AdvancedRoute::controller('/', 'DashBoardController');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/* Route::get('/', function () {
  return view('welcome');
  });
 */
Route::group(['prefix' => LaravelLocalization::setLocale() , 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function() {
    AdvancedRoute::controller('auth', 'AuthController');
    Route::group(['middleware' => ['auth']], function() {
        AdvancedRoute::controller('profile', 'ProfileController');
        AdvancedRoute::controller('notifications', 'NotificationsController');
        Route::group(['middleware' => ['isAdmin'], 'prefix' => 'admin'], function() {
            AdvancedRoute::controller('roles', 'Admin\RolesController');
            AdvancedRoute::controller('users', 'Admin\UsersController');
            AdvancedRoute::controller('posts', 'Admin\PostsController');
            AdvancedRoute::controller('events', 'Admin\EventsController');
            AdvancedRoute::controller('gallery', 'Admin\GalleryController');
            AdvancedRoute::controller('images', 'Admin\ImagesController');
            AdvancedRoute::controller('job_titles', 'Admin\JobTitlesController');
            AdvancedRoute::controller('staff', 'Admin\StaffController');
            AdvancedRoute::controller('messages', 'Admin\MessagesController');
            AdvancedRoute::controller('boards', 'Admin\BoardsController');
            AdvancedRoute::controller('configs', 'Admin\ConfigsController');
            AdvancedRoute::controller('search', 'Admin\SearchController');
            AdvancedRoute::controller('translator', 'Admin\TranslatorController');
            AdvancedRoute::controller('options', 'Admin\OptionsController');
            AdvancedRoute::controller('ajax', 'Admin\AjaxController');
            AdvancedRoute::controller('/', 'Admin\DashBoardController');
        });
    });
    AdvancedRoute::controller('/posts', 'PostsController');
    AdvancedRoute::controller('/gallery', 'GalleryController');
    AdvancedRoute::controller('/events', 'EventsController');
    AdvancedRoute::controller('/staff', 'StaffController');
    AdvancedRoute::controller('/boards', 'BoardsController');
    AdvancedRoute::controller('/messages', 'MessagesController');
    Route::get('/about', 'PagesController@about');
    Route::get('/contact', 'PagesController@contact');
    AdvancedRoute::controller('/', 'HomeController');
});


Route::prefix('api')->group(function () {
    require_once __DIR__ . '/api.php';
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon;

class Post extends \App\Models\BaseModel {

    use SoftDeletes,
        \App\Models\Traits\CreatedBy,
        \App\Models\Traits\HasAttach,
        \Laravel\Scout\Searchable,
        \Spatie\Translatable\HasTranslations;

    ///////////////////////////// has translation
    public $translatable = ['title', 'tags', 'slug', 'content', 'meta_description', 'meta_keywords'];
    protected $table = "posts";
    protected $guarded = [
        'deleted_at',
        'image',
        'logged_user'
    ];
    protected $hidden = [
        'deleted_at',
    ];
    protected static $attachFields = [
        'image' => [
            'sizes' => ['small' => 'crop,240x180', 'large' => 'resize,720x540'],
            'path' => 'uploads'
        ],
    ];
    public $rules = [
        'title' => 'required',
        'slug' => 'required',
        'content' => 'required',
        'image' => 'nullable|image|max:4000'
    ];

    public function toSearchableArray() {
        $array = [
            'id' => $this->id,
            'title' => $this->title,
            'tags' => $this->tags,
            'content' => $this->content,
        ];
        return $array;
    }

    public static function boot() {
        parent::boot();
        static::created(function ($row) {
            if (!request()->hasFile('image') && !$row->image) {
                $image = generateImage('Post Image', ['small' => '240x180', 'large' => '720x540']);
                $data['image'] = $image;
                \DB::table('posts')->where('id', $row->id)->update($data);
            }
        });
    }

    public function scopeActive($query) {
        return $query->where('is_active', '=', 1);
    }

    public function getData() {
        return $this;
    }

    public function export($rows, $fileName) {
        if ($rows) {
            foreach ($rows as $row) {
                unset($object);
                $object['id'] = $row->id;
                $object['Title'] = $row->title;
                $object['Content'] = $row->content;
                $object['Tags'] = $row->tags;
                $object['Is Active'] = ($row->is_active) ? trans('app.Yes') : trans('app.No');
                $object['Created at'] = $row->created_at;
                $labels = array_keys($object);
                $data[] = $object;
            }
            export($data, $labels, $fileName);
        }
    }

    public function getLinkAttribute() {
        return lang() . '/posts/details/' . $this->id . '/' . $this->slug;
    }

    public function getTitleLimitedAttribute() {
        return str_limit($this->title, 35);
    }

    public function getContentLimitedAttribute() {
        return str_limit(strip_tags($this->content), 60);
    }

}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

class PostsController extends \App\Http\Controllers\Controller {

    public $model;
    public $module;

    public function __construct(\App\Models\Post $model) {
        $this->module = 'admin/posts';
        $this->title = trans('app.Posts');
        $this->model = $model;
        $this->rules = $model->rules;
    }

    public function getIndex() {
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.List') . " " . $this->title;
        $data['rows'] = $this->model->getData()->latest()->paginate(env('PAGE_LIMIT',10));
        $data['row'] = $this->model;
        return view($this->module . '.index', $data);
    }

    public function getCreate() {
        authorize('create-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.Create') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['row'] = $this->model;
        $data['row']->is_active = 1;
        return view($this->module . '.create', $data);
    }

    public function postCreate() {
        authorize('create-' . $this->module);
        foreach (langs() as $lang) {
            $slug[$lang] = slug(request('title.' . $lang));
        }
        request()->request->add(['slug' => $slug]);
        $this->validate(request(), $this->rules);
        if ($row = $this->model->create(request()->all())) {
            flash()->success(trans('app.Created successfully'));
            return redirect(lang() . '/' . $this->module);
        }
        flash()->error(trans('app.failed to save'));
    }

    public function getEdit($id) {
        authorize('edit-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.Edit') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['row'] = $this->model->findOrFail($id);
        return view($this->module . '.edit', $data);
    }

    public function postEdit($id) {
        authorize('edit-' . $this->module);
        foreach (langs() as $lang) {
            $slug[$lang] = slug(request('title.' . $lang));
        }
        request()->request->add(['slug' => $slug]);
        $row = $this->model->findOrFail($id);
        $this->validate(request(), $this->rules);
        if ($row->update(request()->all())) {
            flash(trans('app.Update successfully'))->success();
            return back();
        }
    }

    public function getView($id) {
        authorize('view-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.View') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['row'] = $this->model->findOrFail($id);
        return view($this->module . '.view', $data);
    }

    public function getDelete($id) {
        authorize('delete-' . $this->module);
        $row = $this->model->findOrFail($id);
        $row->delete();
        flash()->success(trans('app.Deleted Successfully'));
        return back();
    }

    public function getExport() {
        authorize('view-' . $this->module);
        $rows = $this->model->getData()->get();
        if ($rows->isEmpty()) {
            flash()->error(trans('app.There is no results to export'));
            return back();
        }
        $this->model->export($rows, $this->module);
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

class PostsController extends \App\Http\Controllers\Controller {

    public $module;

    public function __construct(\App\Models\Post $model) {
        $this->module = 'posts';
        $this->views='front.'.$this->module;
        $this->model = $model;
    }

    public function getIndex() {
        $data['page_title'] = trans('front.Posts');
        $data['meta_description'] =$data['page_title'] ;
        $data['meta_keywords'] = $data['page_title'] ;
        $data['image'] = conf('logo');
        $data['rows']=$this->model->getData()->active()->latest()->paginate(env('PAGE_LIMIT',10));
        return view($this->views . '.index', $data);
    }
    public function getDetails($id,$slug=NULL) {
        $data['row']=  $this->model->findOrFail($id);
        $data['page_title'] = $data['row']->title;
        $data['meta_description'] =$data['row']->meta_description;
        $data['meta_keywords'] = $data['row']->meta_keywords;
        $data['image'] =$data['row']->image;
        $data['row']->increment('views_count');
        return view($this->views . '.details', $data);
    }
}

resources/views/front/posts/details.blade.php
@extends('front.layouts.master')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="section-title-wrapper">
            <div class="section-title mt-20">
                <h3>{{$page_title}}</h3>
                <p></p>
            </div>
        </div>
    </div>
</div>
<!--News Details Area Start-->
<div class="news-details-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-12">
                <div class="news-details-content">
                    <div class="single-latest-item">
                        <img src="uploads/large/{{$row->image}}" alt="{{$row->title}}">
                        <div class="single-latest-text">
                            <h3>{{$row->title}}</h3> 
                            <div class="single-item-comment-view">
                                <span><i class="zmdi zmdi-calendar-check"></i>{{$row->created_at->format('F j, Y')}}</span>
                                <span><i class="zmdi zmdi-eye"></i>{{$row->views_count}}</span>
                            </div>
                            <p>{!! $row->content !!}</p>
                            <div class="tags-and-links">
                                @if($row->tags)
                                <div class="related-tag">
                                    <span>{{trans('front.Tags')}}:</span>
                                    <ul class="tags">
                                        @foreach(explode(',',$row->tags) as $tag)
                                        <li><a href="{{lang()}}/posts?q={{$tag}}">{{$tag}},</a></li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                                <div class="social-links">
                                    <span>{{trans('front.Share')}}:</span>
                                    <a href="https://facebook.com/sharer/sharer.php?u={{app()->make("url")->to('/')}}/{{$row->link}}" target="_blank"><i class="zmdi zmdi-facebook"></i></a>
                                    <a href="https://twitter.com/intent/tweet?url={{app()->make("url")->to('/')}}/{{$row->link}}" target="_blank"><i class="zmdi zmdi-twitter"></i></a>
                                    <a href="https://www.linkedin.com/shareArticle?url={{app()->make("url")->to('/')}}/{{$row->link}}" target="_blank"><i class="zmdi zmdi-linkedin"></i></a>
                                    <a href="https://web.whatsapp.com/send?text={{app()->make("url")->to('/')}}/{{$row->link}}" target="_blank"><i class="zmdi zmdi-whatsapp"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>    
            </div>
            
        </div>
    </div>
</div>
<!--End of News Details Area-->
@endsection

resources/views/front/posts/index.blade.php
@extends('front.layouts.master')

@section('content')
<div class="latest-area section-padding bg-white">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title mt-20">
                        <h3>{{$page_title}}</h3>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @if (!$rows->isEmpty())
            @foreach ($rows as $row)
            @include('front.posts.single')
            @endforeach
            <div class="container">
                <div class="paganition-center center"> 
                    {!! $rows->appends(['q'=>request('q')])->render() !!}
                </div>
            </div>
            @else
            {{trans("front.There is no results")}}
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/front/posts/single.blade.php
<div class="col-lg-6 col-md-12 col-12">
    <div class="single-latest-item">
        <div class="single-latest-image">
            <a href="{{$row->link}}">
                <img src="uploads/small/{{$row->image}}" alt="{{$row->title}}">
            </a>
        </div>
        <div class="single-latest-text">
            <h3>
                <a href="{{$row->link}}">
                    {{$row->title_limited}}
                </a>
            </h3>
            <div class="single-item-comment-view">
                <span><i class="zmdi zmdi-calendar-check"></i>{{$row->created_at->format('F j, Y')}}</span>
                <span><i class="zmdi zmdi-eye"></i>{{$row->views_count}}</span>
            </div>
            <p>
                {{$row->content_limited}}
            </p>
            <a href="{{$row->link}}" class="button-default">{{trans('front.More')}}</a>
        </div>
    </div>
</div>